mercure:
    hubs:
        default:
            # Adres wewnętrzny w Dockerze dla publishera (backend -> mercure)
            url: "%env(MERCURE_URL)%"
            # Publiczny URL dla subskrybentów (przeglądarka -> mercure)
            public_url: "%env(MERCURE_PUBLIC_URL)%"
            # Sekret JWT do podpisywania tokenów (z .env)
            jwt:
                secret: "%env(MERCURE_JWT_SECRET)%"
                publish: ["*"]
                subscribe: ["*"]
