mercure:
    hubs:
        default:
            # Adres Twojego Mercure hubu, bierze wartość z .env
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_URL)%'
            # Sekret JWT do podpisywania tokenów (z .env)
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: ["*"]
                subscribe: ["*"]