# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\MqttService:
        arguments:
            $broker: "%env(MQTT_BROKER)%"
            $port: "%env(int:MQTT_PORT)%"
            $clientId: "%env(MQTT_CLIENT_ID)%"

    App\Service\NotifierService:
        arguments:
            $mercureUrl: "%env(MERCURE_URL)%"

    App\Service\HealthCheckService:
        arguments:
            $mqttBroker: "%env(MQTT_BROKER)%"
            $mqttPort: "%env(int:MQTT_PORT)%"
            $mercureHealthUrl: "http://mercure:3000/healthz"
            $raspberryUrl: "%env(RASPBERRY_PI_URL)%"
            $chessEngineUrl: "%env(CHESS_ENGINE_URL)%"

    App\Command\MqttListenCommand:
        arguments:
            $mqtt: '@App\Service\MqttService'
            $game: '@App\Service\GameService'
            $notifier: '@App\Service\NotifierService'
            $state: '@App\Service\StateStorage'
            $logger: "@?logger"
